server:
  host: "127.0.0.1"
  port: 8080
  mode: "debug"
  read_timeout: 60
  write_timeout: 60

ai:
  base_url: "https://ark.cn-beijing.volces.com/api/v3"
  api_key: ""
  model_id: "deepseek-r1-distill-qwen-32b-250120"
  prompt_file_path: "doc/system_prompt.md"